export const COUNTRY_NAMES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const COUNTRIES = COUNTRY_NAMES.map(name => ({
  value: name,
  label: name
}));

export const COUNTRY_CODE_MAP: Record<string, string> = {
  "uk": "United Kingdom",
  "gb": "United Kingdom",
  "us": "United States",
  "de": "Germany",
  "fr": "France",
  "gh": "Ghana",
  "br": "Brazil",
  "pt": "Portugal",
  "ng": "Nigeria",
  "ee": "Estonia",
  "es": "Spain",
  "ch": "Switzerland",
  "ke": "Kenya",
  "sg": "Singapore",
  "it": "Italy",
  "uae": "United Arab Emirates"
};

export function formatCountryDisplay(country: string): string {
  if (!country) return "";
  const name = country.trim();
  
  // Handlers for standard short codes
  const codeMapDisplay: Record<string, string> = {
    "uk": "UK",
    "gb": "UK",
    "us": "US",
    "uae": "UAE",
    "de": "Germany",
    "fr": "France",
    "gh": "Ghana",
    "br": "Brazil",
    "pt": "Portugal",
    "ng": "Nigeria",
    "ee": "Estonia",
    "es": "Spain",
    "ch": "Switzerland",
    "ke": "Kenya",
    "sg": "Singapore",
    "it": "Italy"
  };
  
  const lowerName = name.toLowerCase();
  if (codeMapDisplay[lowerName]) {
    return codeMapDisplay[lowerName];
  }
  
  // Custom abbreviations for common long country names
  const abbreviations: Record<string, string> = {
    "United Kingdom": "UK",
    "United States": "US",
    "United Arab Emirates": "UAE",
    "Democratic Republic of the Congo": "DR Congo",
    "Central African Republic": "CAR",
    "Saint Vincent and the Grenadines": "St. Vincent",
    "Bosnia and Herzegovina": "Bosnia",
    "Antigua and Barbuda": "Antigua"
  };
  
  if (abbreviations[name]) {
    return abbreviations[name];
  }
  
  if (name.length > 15) {
    const words = name.split(/\s+/).filter(w => w[0] === w[0]?.toUpperCase() && w[0]?.match(/[A-Z]/));
    if (words.length > 1) {
      return words.map(w => w[0]).join("");
    }
    return name.slice(0, 15) + "...";
  }
  
  return name;
}


